services:
  customer-db:
    container_name: customer-db
    image: postgres:alpine
    environment:
      POSTGRES_USER: dmitri
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_MULTIPLE_DATABASES: customer,fraud,notification
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-examreg-db:/var/lib/data/postgres
    ports:
      - "5433:5432"
    networks:
      - reg-db-ntwk
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-examreg-db:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - reg-db-ntwk
    restart: unless-stopped


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - exmmicros
    ports:
      - 9411:9411

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - exmmicros
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - exmmicros
  api-gateway:
    image: dmitriikonnovnn/apigateway:1.0-SNAPSHOT
    container_name: api-gateway
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - exmmicros
    depends_on:
      - zipkin
      - eureka-server
  eureka-server:
    container_name: eureka-server
    image: dmitriikonnovnn/eureka-server:1.0-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - exmmicros
    depends_on:
      - zipkin

  customer:
    container_name: customer
    image: dmitriikonnovnn/customer:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - reg-db-ntwk
      - exmmicros
    depends_on:
      - customer-db
      - zipkin
      - eureka-server
      - rabbitmq

  fraudcheck:
    container_name: fraud-check
    image: dmitriikonnovnn/fraudcheck:1.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - reg-db-ntwk
      - exmmicros
    depends_on:
      - customer-db
      - zipkin
      - eureka-server
      - rabbitmq
  notification:
    container_name: notification
    image: dmitriikonnovnn/notifications:1.0-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - exmmicros
    depends_on:
      - zipkin
      - eureka-server
      - rabbitmq



networks:
  reg-db-ntwk:
    driver: bridge
  exmmicros:
    driver: bridge

volumes:
  postgres-examreg-db:
  pgadmin-examreg-db: