apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  template:
    metadata:
      name: notification
      labels:
        app: notification
        tier: backend
    spec:
      containers:
        - name: notification
          image: dmitriikonnovnn/notifications:1.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                    key: spring_profiles_active
                    name: mc-services-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: notification_service_username
                  name: mc-services-secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: spring_datasource_new_url_notification
                  name: mc-services-config
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: notification_service_password
                  name: mc-services-secret
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification


---

apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - port: 80
      targetPort: 8082
  type: NodePort
