init u:
	terraform init -upgrade
	terraform fmt
	terraform validate
	terraform plan
init:
	terraform init
	terraform fmt
	terraform validate
	terraform plan
plan:
	terraform fmt
	terraform validate
	terraform plan
apply:
	terraform apply
destroy:
	terraform destroy
