iu:
	terraform init -upgrade
	terraform fmt
	terraform validate
	terraform plan
i:
	terraform init
	terraform fmt
	terraform validate
	terraform plan
p:
	terraform fmt
	terraform validate
	terraform plan
a:
	terraform apply
d:
	terraform destroy
