apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudcheck
  labels:
    app: fraudcheck
spec:
  replicas: 1
  template:
    metadata:
      name: fraudcheck
      labels:
        app: fraudcheck
        tier: backend
    spec:
      containers:
        - name: fraudcheck
          image: dmitriikonnovnn/fraudcheck:1.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                    key: spring_profiles_active
                    name: mc-services-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: postgres_username
                  name: mc-services-config
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: spring_datasource_url_fraud
                  name: mc-services-config
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: mc-services-secret
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraudcheck

---

apiVersion: v1
kind: Service
metadata:
  name: fraudcheck
spec:
  selector:
    app: fraudcheck
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      nodePort: 30032
  type: NodePort
