apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudcheck
  labels:
    app: fraudcheck
spec:
  replicas: 1
  template:
    metadata:
      name: fraudcheck
      labels:
        app: fraudcheck
        tier: backend
    spec:
      containers:
        - name: fraudcheck
          image: dmitriikonnovnn/fraudcheck:1.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: fraudcheck

---

apiVersion: v1
kind: Service
metadata:
  name: fraudcheck
spec:
  selector:
    app: fraudcheck
  ports:
    - port: 80
      targetPort: 8081
  type: NodePort
