apiVersion: v1
kind: Secret
metadata:
  name: mc-services-secret
type: Opaque
data:
  postgres_password: QVZOU183Q2lBdlVMUzBqTmR5ZHRyOVl3
  postgres_username: ZG9hZG1pbg==
  notification_service_username: bm90aWZpY2F0aW9uLXNlcnZpY2U=
  notification_service_password: QVZOU185TmlaTVRXMTRDLXFramhuWklK
  fraud_service_username: ZnJhdWQtc2VydmljZQ==
  fraud_service_password: QVZOU19neDVQRGR6dzlrYVFPVC0xR2M2
  customer_service_username: Y3VzdG9tZXItc2VydmljZQ==
  customer_service_password: QVZOU18wNGQ5UjVNR3E1cTZNRnc3YTVu

